mail.send=false

# Email service config
mail.smtp.host=smtp.gmail.com
mail.smtp.port=465
mail.smtp.ssl.enable=true
mail.smtp.starttls.enable=true
mail.smtp.auth=true

# Credentials
username=
password=

sender=
# Multiple recipients should be separated by semicolon(;)
recipients.to=
recipients.cc=
subject=
body=